### ISSUE TITLE
Availability of the caml-list archive

### ISSUE THREAD

**Issue by gasche** [ocaml/ocaml.org#706] opened 2022-12-15 05:50 UTC
On the [Community page](https://ocaml.org/community), the [Mailing list](https://inbox.ocaml.org/caml-list/) link (<https://inbox.ocaml.org/caml-list/>) appears to be dead.

I hit this issue while trying to locate the recommended/current/pleasant archives for the caml-list. I have not found such archives -- the best I had were located on inria.fr, but only contain older posts. Funnily enough, looking for this finds [this reply](https://sympa.inria.fr/sympa/arc/caml-list/2015-12/msg00122.html) in 2015 which contains an issue link that is itself dead (the ocaml.org repo rename made those links invalid) but is actually https://github.com/ocaml/v2.ocaml.org/issues/704.

I'm curious if anyone knows of the current recommend link to caml-list archives.

**Comment by cuihtlauac** [comment] 2022-12-15 16:40
I believe inbox.ocaml.org being dead is a duplicate of: https://github.com/ocaml/ocaml.org/issues/550

I agree the availability of the archives of the caml-list is an issue. Shall we create an issue on this matter?

**Comment by tmattio** [comment] 2022-12-15 16:44
There's also some discussions on https://github.com/ocaml/infrastructure/issues/15

**Comment by tmattio** [comment] 2022-12-15 16:47
> I agree the availability of the archives of the caml-list is an issue. Shall we create an issue on this matter?

Yes, I suggest we re-open the current issue and rename it to be specific to the access to caml-list archives. (and track inbox.ocaml.org on the issue you linked to)

FWIW, I find https://github.com/ocaml/v2.ocaml.org/issues/704 to be a very good suggestion: we could have the archive of the mailing lists available on ocaml.org

**Comment by gasche** [comment] 2022-12-15 20:48
@cuihtlauac in #550, @leahneukirchen points that at a mirror https://inbox.vuxu.org/caml-list/ . Could we use it as a replacement link in ocaml.org as long as inbox.ocaml.org is down?

**Comment by leahneukirchen** [comment] 2022-12-16 00:50
Feel free to!

**Comment by cuihtlauac** [comment] 2022-12-16 09:40
Fix: https://github.com/ocaml/ocaml.org/pull/712

**Comment by cuihtlauac** [comment] 2022-12-16 13:47
Fix: https://github.com/ocaml/ocaml.org/pull/712

**Closed as completed by cuihtlauac** 2022-12-16 13:47 UTC
Labels: bug, data, infrastructure
