### ISSUE TITLE
The documentation for OCaml < 4.12 is not accessible anymore

### ISSUE THREAD

**Issue by kit-ty-kate** [ocaml/ocaml.org#1869] opened 2023-12-19 17:00 UTC
Steps to reproduce:
1. go to https://ocaml.org/releases
2. click on the `Standard API Library` link OCaml 4.11.2 (https://v2.ocaml.org/releases/4.11/api/index.html)

the result will be a blank page (secretely a 404 according to the console)

**Comment by sabine** [comment] 2024-01-08 16:43
Duplicate of #1844

**Closed as completed by sabine** 2024-01-08 16:43 UTC
