### ISSUE TITLE
Markdown/HTML files rendered as “modules” in /doc

### ISSUE THREAD

**Issue by cuihtlauac** [ocaml/ocaml.org#630] opened 2022-11-18 15:32 UTC
When looking at project documentation files using their `/doc` path, they appear as if they were modules.

Here are a couple of examples:

* https://ocaml.org/p/memprof-limits/0.2.0/doc/recovering.html
* https://ocaml.org/p/omd/2.0.0~alpha2/doc/README.md.html
* https://ocaml.org/p/omd/2.0.0~alpha2/doc/CHANGES.md.html
* https://ocaml.org/p/omd/2.0.0~alpha2/doc/LICENSE.html

The faulty code seems to be here:

https://github.com/ocaml/ocaml.org/blob/main/src/ocamlorg_package/lib/ocamlorg_package.ml#L278

Documentation item variant for markdown and HTML content seems to be missing.

**Comment by sabine** [comment] 2022-11-18 15:40
A patch for this is is upcoming. When odoc emits HTML-fragments+metadata, we get both the missing preamble back and ocaml.org will no longer parse the breadcrumbs from the URL path (the metadata includes correct breadcrumbs). :+1:

**Comment by sabine** [comment] 2022-11-23 17:17
Duplicate of https://github.com/ocaml/ocaml.org/issues/583

**Closed as completed** 2022-11-23 17:19 UTC
