### ISSUE TITLE
Markdown table are broken on package overview

### ISSUE THREAD

**Issue by xvw** [ocaml/ocaml.org#85] opened 2021-09-01 15:28 UTC
Hi. The package application is very cool, thanks a lot, but even table works pretty well from Odoc, on Markdown, it seems broken: https://v3.ocaml.org/p/preface/0.1.0

(the extremely large table (`----|----`) is due to markdown linter).

ps: I don't know if I have to submit the report here or on the front-end part.

**Comment by ifazk** [comment] 2022-01-14 21:50
Posting this here to save anyone else the trouble of trying to figure out what's going on. Feel free to correct me if I got something wrong here.

This is a an upstream issue and duplicate #59. The most relevant upstream issue is https://github.com/ocaml/omd/issues/205

**Comment by cuihtlauac** [comment] 2022-12-05 10:19
Duplicate of: https://github.com/ocaml/ocaml.org/issues/59

**Closed as completed by cuihtlauac** 2022-12-05 10:19 UTC
Labels: bug, package, upstream
