### ISSUE TITLE
Recently updated packages should show time since latest update

### ISSUE THREAD

**Issue by axrwl** [ocaml/ocaml.org#335] opened 2022-03-03 06:01 UTC
In the recently updated category of the [packages](https://v3.ocaml.org/packages) page, each package listed displays its most recent version. But it will be nicer to display the time spent since that version was released along with it.

**Comment by tmattio** [comment] 2022-03-08 11:12
Closing as a duplicate of #40

**Closed as completed by tmattio** 2022-03-08 11:12 UTC
