### ISSUE TITLE
Improvement to the Multicore Example in Playground

### ISSUE THREAD

**Issue by sabine** [ocaml/ocaml.org#824] opened 2023-01-17 08:01 UTC
There were concerns about the multicore Fibonacci code example misrepresenting the skills of OCaml programmers, as it shows an inefficient implementation.

Suggestion from [discuss.ocaml.org](https://discuss.ocaml.org/t/looking-for-participants-for-user-survey-on-ocaml-org-package-documentation-and-learn-area/11128/18):
> Rename the function to `naive_fib` and point to this URL in a comment just above the function name?
> 
> [See: OPCEB chapter 8 on memoization for a more performant implementation](https://cs3110.github.io/textbook/chapters/ds/memoization.html#fibonacci)

**Comment by cuihtlauac** [comment] 2023-01-17 08:28
Relevant discussion on twitter: https://twitter.com/wicko3/status/1482042995138600960

**Comment by cuihtlauac** [comment] 2023-01-17 08:35
Possible duplicate of: https://github.com/ocaml/ocaml.org/issues/233

**Closed as completed** 2023-01-19 15:29 UTC
Labels: enhancement, playground
