### ISSUE TITLE
Search packages input not centered on medium screens

### ISSUE THREAD

**Issue by MelakuAlehegn** [ocaml/ocaml.org#1677] opened 2023-10-18 14:02 UTC
@sabine  @SaySayo  On packages page the package search input is not centered for screens between 768-1023px, I just taught centering this will give a better UX, can you check that.

how it looks on medium screens
![uncentered](https://github.com/ocaml/ocaml.org/assets/49185991/7ea9ec79-8110-4471-bd8f-fef8d4d6a235)

how it was supposed to look 

![image](https://github.com/ocaml/ocaml.org/assets/49185991/18d3992c-7460-4c6b-9697-fcb37b155335)

mobile view
![image](https://github.com/ocaml/ocaml.org/assets/49185991/2447b2b6-ced6-434d-bffb-89b90a01c294)

**Comment by sabine** [comment] 2023-10-18 15:31
Cannot reproduce. I think this was resolved by https://github.com/ocaml/ocaml.org/pull/1665

**Closed as completed by sabine** 2023-10-18 15:31 UTC
