### ISSUE TITLE
switching the ocaml version in the documentation should keep the url

### ISSUE THREAD

**Issue by tcoopman** [ocaml/ocaml.org#327] opened 2022-02-22 12:27 UTC
For example when you're looking at: https://v3.ocaml.org/p/ocaml-base-compiler/4.13.1/doc/Str/index.html#splitting and you switch the ocaml version to 4.14.0~beta1 the page switches to https://v3.ocaml.org/p/ocaml-base-compiler/4.14.0~beta1

I would expect the page to jump to: https://v3.ocaml.org/p/ocaml-base-compiler/4.14.0~beta1/doc/Str/index.html#splitting

**Comment by tmattio** [comment] 2022-02-22 14:40
Thanks for the issues @tcoopman, closing as a duplicate of https://github.com/ocaml/ocaml.org/issues/138

**Closed as completed by tmattio** 2022-02-22 14:40 UTC
