### ISSUE TITLE
Playground ignores last statement unless it ends with a new line

### ISSUE THREAD

**Issue by Timmmm** [ocaml/ocaml.org#733] opened 2022-12-26 12:38 UTC
If you put `1+2;;` into the playground and hit Run, nothing happens. If you add a new line after the `;;` it works as expected.

Took me ages to figure this out. Very confusing for a beginner, trust me!

I guess an easy fix is to add an extra newline somewhere maybe on this line? https://github.com/ocaml/ocaml.org/blob/main/src/ocamlorg_playground/main.ml#L137

To be honest I couldn't figure out why that line adds `;;` so maybe it's not the right place.

**Comment by cuihtlauac** [comment] 2022-12-28 11:21
Thanks @Timmmm. Nice observation, I hadn't figured out that. You're right this needs to be fixed. There are a number of issues with the playground: https://github.com/ocaml/ocaml.org/issues/717

**Comment by tmattio** [comment] 2023-01-06 11:16
Looks like @cuihtlauac and I can't reproduce anymore, so closing for now, but feel free to re-open if you see the bug happen again

**Closed as completed by tmattio** 2023-01-06 11:16 UTC
Labels: bug, playground
