### ISSUE TITLE
support other README formats

### ISSUE THREAD

**Issue by hyphenrf** [ocaml/ocaml.org#287] opened 2022-02-08 14:45 UTC
similar to `README.md` and `README.org`(#30), some repositories use plaintext (just `README` or `README.txt`), `.rst`, `.markdown`, etc.. And some repos use `readme` or `Readme` instead of `README` Right now, such files aren't getting picked up in the package description.

**Comment by tmattio** [comment] 2022-02-08 15:55
Thanks @hyphenrf - closing as a duplicate of https://github.com/ocaml/v3.ocaml.org-server/issues/30

**Closed as completed by tmattio** 2022-02-08 15:55 UTC
